name: idobata
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter
  window_manager_plus: ^1.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
